name: Create Zip
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'CreativeCraftPlus.zip'
        exclusions: '.github, manifest.json, mmc-pack.json'
    - name: Upload Release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "CreativeCraftPlus.zip"
        token: ${{ secrets.GITHUBTOKEN }}
