name: Create Zip
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'CreativeCraftPlus.zip'
        exclusions: '.github, manifest.json, mmc-pack.json'
    - name: Release
      id: bump
      uses: zwaldowski/match-label-action@v1
      with:
        allowed: major,minor,patch
    - uses: zwaldowski/semver-release-action@v1
      with:
        bump: ${{ steps.bump.outputs.match }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
